### ISSUE TITLE
Переключение цветов 

### ISSUE THREAD

**Issue by anasthezia** [lorushan/task_1#3]
Блок с классом  .color-change__circles на страницах "main" и "product" 
1. Кружочки с цветами выводятся с помощью тега  div без класса. Во первых, одинаковые элементы лучше делать с помощью списков (ul), во-вторых у этих элементов обязательно должен быть какой-то класс, иначе они могут унаследовать что-то ненужное
2. Здесь не нужно жёстко задавать цвета через css с помощью псевдо-классво nth-child, так как в реальности у разных моделей товаров могут быть разные наборы ветов. Например у одного товара - белый, синий, красный, у второго - белый, красный, чёрный, у третьего - только красный. Здесь лучше использовать БЭМ-модификаторы (они прописываются через одинарное нижнее подчёркивание)ю Например <div class="product__circle product-circle_red"> ... </div>

**Comment by ivan-q** [comment]
Я создал модификаторы и добавил их через js используя nth-child(). Но это, как я понимаю, не очень хороший подход. И я пока не знаю, как это реализовать. Можно пример? Просто здесь в описании проблемы после слова "Например" ничего нет)

**Comment by anasthezia** [comment]
Сорри, не видела что обрезалось 
Ну ты уже почти правильно исправил, только зачем так js-ом жёстко навешивать? Можно взять вожно задать массив цветов и в цикле его перебрать. В итоге должно получиться 
`<ul class="color-change__circles">`
`<li class="color-change__circle color-change__circle_red">...</li>`
`<li class="color-change__circle color-change__circle_white">...</li>`
`<li class="color-change__circle color-change__circle_black">...</li>`
`</ul>`
Далее в стилях ты описываешь класс  `color-change__circle` (размеры,  радиус и тд). а для классов-модификаторов прописываешь только то свойство, которое они изменяют (цвет)
